### ISSUE TITLE
Missing example of Ruby installation for Developer Setup

### ISSUE THREAD

**Issue by gbraad** [ManageIQ/guides#111]
The document [developer_setup.md](https://github.com/ManageIQ/guides/blob/master/developer_setup.md) mentions the need of Ruby 2.2.2+ under the heading _Install Ruby_, but it does not give an example of what to do in case people are unfamiliar to the use of a version manager.

**Comment by gbraad** [comment]
Fiirst get the requirements to perform a build of a newer Ruby version

```bash
sudo yum install -y git-core zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison curl sqlite-devel
git clone git://github.com/sstephenson/rbenv.git .rbenv
echo 'export PATH="$PATH:$HOME/.rbenv/bin"' >> ~/.bash_profile
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$PATH:$HOME/.rbenv/plugins/ruby-build/bin"' >> ~/.bash_profile
source ~/.bash_profile
```

and then use the following to perform an install of Ruby 2.2.4
```
rbenv install -v 2.2.4
rbenv global 2.2.4
```

**Comment by chessbyte** [comment]
Addressed in https://github.com/ManageIQ/guides/pull/199
