### ISSUE TITLE
Required PostgreSQL version is now 9.5, developer guide still states 9.4

### ISSUE THREAD

**Issue by abonas** [ManageIQ/guides#135]
After the latest rebase on miq master, I noticed that required PostgreSQL version is now 9.5, but the documentation still says 9.4.
Please update the developer guide accordingly.
thanks!
cc @chessbyte @Fryguy

**Comment by selmanj** [comment]
I'm using PostgreSQL version 9.4 and haven't encountered any issues; can you describe what specifically requires 9.5?

**Comment by sergio-ocon** [comment]
In the last sprint review there was a comment that this was needed for replication and HA in the future.

**Comment by abonas** [comment]
iirc it was also due some usage of specific data types, but I can't recall exact details. what I can say is that for me it started failing after rebase and then I saw the new requirement, and opened this issue.

**Comment by carbonin** [comment]
PostgreSQL 9.5 is not required for development. 9.4 is still the correct minimum. This issue can be closed @Fryguy
