### ISSUE TITLE
Developer setup guide requires PostgreSQL 9.4, but CentOS 7 provides 9.2

### ISSUE THREAD

**Issue by selmanj** [ManageIQ/guides#140]
The developer guide describes setting up a dev environment in CentOS 7, but the version of PostgreSQL provided is 9.2.

I was able to work around this by adding a PostgreSQL-provided repo.

**Comment by sergio-ocon** [comment]
CentOS provides software collections, that includes 9.4, and that are used when building the appliance

**Comment by selmanj** [comment]
@sergio-ocon Note that I'm speaking about the developer setup guide, not the built image.

For Centos 7, I only see postgres-9.2:
http://mirror.centos.org/centos/7/os/x86_64/Packages/
http://mirror.centos.org/centos/7/updates/x86_64/Packages/

The PostgreSQL website summarizes the versions nicely: https://www.postgresql.org/download/linux/redhat/

The guide instructs to install the EPEL, but that does not include postgresql.

**Comment by carbonin** [comment]
Commit eee47180ba456cbc554179d8231fbc3531f24d42 also contributed to this fix.
