### ISSUE TITLE
Broken link on architecture->providers page

### ISSUE THREAD

**Issue by jameswnl** [ManageIQ/guides#158]
The ```Containers Manager``` link is invalid in section: https://github.com/ManageIQ/guides/blob/master/architecture/providers_overview.md#provider-manager-types

Probably should be removed.

**Comment by jameswnl** [comment]
@miq-bot add_labels hacktoberfest

**Comment by jameswnl** [comment]
@miq-bot add_labels hacktoberfest

**Comment by Fryguy** [comment]
Closed by #159
