### ISSUE TITLE
Deploying_RDO_using_Instack url not valid

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/guides#198]
This link in readme is broken.

https://www.rdoproject.org/Deploying_RDO_using_Instack#Deploying_RDO_using_Instack

**Comment by Fryguy** [comment]
@tzumainn Can you take a look at this one?

**Comment by tzumainn** [comment]
Ah, looks like that link is now outdated.  Here's a PR that updates it to the current one: https://github.com/ManageIQ/guides/pull/200

**Comment by Fryguy** [comment]
Closed in #200
