### ISSUE TITLE
Ubuntu developer setup does not work

### ISSUE THREAD

**Issue by jzuilkowski** [ManageIQ/guides#244]
Using rbenv, and following the directions, bin/setup fails to properly configure the database.

Missing from the instructions are versions, almost none are listed.

I've burned almost two days on this already.

Here is the result of bin/setup:

== Migrating database ==
bower not-cached    https://github.com/himdel/jquery.observe_field.git#~0.1.0
bower resolve       https://github.com/himdel/jquery.observe_field.git#~0.1.0
bower not-cached    https://github.com/himdel/spice-html5-bower.git#~1.6.3
bower resolve       https://github.com/himdel/spice-html5-bower.git#~1.6.3
rails aborted!
LoadError: No such file to load -- environment_management
/home/jonz/RubymineProjects/manageiq/lib/extensions/as_include_concern.rb:54:in `rescue in include_concern'
/home/jonz/RubymineProjects/manageiq/lib/extensions/as_include_concern.rb:49:in `include_concern'
/home/jonz/RubymineProjects/manageiq/app/models/miq_server.rb:8:in `<class:MiqServer>'
/home/jonz/RubymineProjects/manageiq/app/models/miq_server.rb:3:in `<top (required)>'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings/database_source.rb:70:in `my_server'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings/database_source.rb:39:in `resource'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings/database_source.rb:60:in `settings_holder'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings/database_source.rb:43:in `load'
/home/jonz/RubymineProjects/manageiq/lib/patches/config_patch.rb:3:in `reload!'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings.rb:59:in `for_resource'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings.rb:18:in `init'
/home/jonz/RubymineProjects/manageiq/config/application.rb:140:in `block in <class:Application>'
/home/jonz/RubymineProjects/manageiq/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
LoadError: No such file to load -- miq_apache
/home/jonz/RubymineProjects/manageiq/app/models/miq_server/environment_management.rb:1:in `<top (required)>'
/home/jonz/RubymineProjects/manageiq/lib/extensions/as_include_concern.rb:51:in `include_concern'
/home/jonz/RubymineProjects/manageiq/app/models/miq_server.rb:8:in `<class:MiqServer>'
/home/jonz/RubymineProjects/manageiq/app/models/miq_server.rb:3:in `<top (required)>'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings/database_source.rb:70:in `my_server'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings/database_source.rb:39:in `resource'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings/database_source.rb:60:in `settings_holder'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings/database_source.rb:43:in `load'
/home/jonz/RubymineProjects/manageiq/lib/patches/config_patch.rb:3:in `reload!'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings.rb:59:in `for_resource'
/home/jonz/RubymineProjects/manageiq/lib/vmdb/settings.rb:18:in `init'
/home/jonz/RubymineProjects/manageiq/config/application.rb:140:in `block in <class:Application>'
/home/jonz/RubymineProjects/manageiq/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by jzuilkowski** [comment]
I have tried this again with Fedora 25 using this playbook - https://github.com/sergio-ocon/manageiq-vagrant-dev/blob/master/scripts/playbook.yml

And still I get the above errors.  Any idea on how I can get past this?

**Comment by jzuilkowski** [comment]
I finally got this to work under Fedora 25, not sure how exactly.  If I can ever get this to work under Ubuntu, I'll update the guide

**Comment by Fryguy** [comment]
LoadError: No such file to load -- environment_management was an error that occurred briefly where the repos were out of sync, but that was quickly resolved and having the latest of the repos should have worked.  @agrare Do you remember having to do anything special for this? @jzuilkowski Do you still have this issue?

**Comment by agrare** [comment]
@Fryguy I just spun up a clean ubuntu-zesty container, followed the steps in the guide and everything came up okay.  I don't see that error on `bin/setup`.

**Comment by jzuilkowski** [comment]
U have not tried again with Ubuntu yet.  I will give it a shot over the next few days and let you know
