### ISSUE TITLE
OpenStack Infra Provider SSH key is not related to (Non-)SSL auth

### ISSUE THREAD

**Issue by aufi** [ManageIQ/guides#323]
There is a misunderstading on meaning of SSH keypair in add OpenStack Infra provider form. It is needed update docs to make clear that SSH keypair is not dependent on Non-SSL/SSL without validation/SSL choice in first panel.

See http://talk.manageiq.org/t/adding-an-openstack-infrastructure-provider/3684/2

**Comment by martinpovolny** [comment]
All right. So if it's for guides then can you make a PR?

If this is something for the product documentation, can you make a BZ or talk to the documentation team, please?

**Comment by aufi** [comment]
Ah, thanks Martin, will make a BZ.
