### ISSUE TITLE
Developer setup specifies Ruby 2.4.x but we're now on Ruby 2.5.x

### ISSUE THREAD

**Issue by mturley** [ManageIQ/guides#371]
According to http://talk.manageiq.org/t/ruby-2-5-x-version-greater-than-2-5-3-is-the-only-supported-ruby-on-ivanchuk/4449, developers should now be using Ruby 2.5.x, so we should update this in the Requirements Summary at the top of the developer guide.

**Comment by Fryguy** [comment]
@jrafanie / @d-m-u Can you take care of this one (and also double check the other versions in this file)?
