### ISSUE TITLE
Provider Generator is not available

### ISSUE THREAD

**Issue by Sdesik1** [ManageIQ/guides#377]
I am new to Manage IQ and followed the instructions to create a provider.
When I click the link i am getting the 404 error.
http://manageiq.org/docs/guides/providers/generator/generator 
Kindly provide the correct link to download the generator.

**Comment by gmcculloug** [comment]
@Sdesik1 Looks like it was renamed to plugins: http://manageiq.org/docs/guides/plugins/generator

We will need to get the link referenced at the bottom of http://manageiq.org/docs/guides/developer_setup/plugins updated.

cc @cmoore-redhat

**Comment by Sdesik1** [comment]
Thanks. I have also requested for some provider configuration information for Nutanix as infrastructure.
