### ISSUE TITLE
In "Extending the UI with buttons, dialogs and executing Ansible Playbooks" developer guide there is a broken link for forms 

### ISSUE THREAD

**Issue by blancett** [ManageIQ/guides#402]
In the following guide Extending the UI with buttons, dialogs and executing Ansible Playbooks (https://www.manageiq.org/docs/guides/ui/provider_plugin). 

The form example for React is broken - gives a 404:

![image](https://user-images.githubusercontent.com/56652758/75690581-1ca72f80-5c71-11ea-9a96-a97b9db4e8db.png)

The link is pointing to https://github.com/ManageIQ/react-ui-components/tree/master/src/amazon-security-form-group

Maybe should go here: https://github.com/ManageIQ/react-ui-components/tree/master/src/forms

**Comment by Fryguy** [comment]
@himdel ?

**Comment by himdel** [comment]
Ah, yes, the example component was not used anywhere.. removed in https://github.com/ManageIQ/react-ui-components/pull/170.

Looking if we can change to a real example..

**Comment by himdel** [comment]
So, we may be able to link to 
https://github.com/ManageIQ/manageiq-providers-lenovo/pull/251
which adds a toolbar and 2 react forms to open.
