### ISSUE TITLE
Update sqlfilter/filter description

### ISSUE THREAD

**Issue by mfalesni** [ManageIQ/guides#49]
The 5.3.2.5 is already telling me that sqlfilter is no longer used but it is not reflected in the REST guide.

**Comment by abellotti** [comment]
Adding support for one or more filter='...' parameters

```
GET <api_url>?filter="..."&filter="..."&filter="..."
```

Syntax for a filter is as follows:

```
filter="attribute op value"
```

By default, filters are logically anded together, for a logical or, prefix the attribute with "or" as follows:

```
filter="or attribute op value"
```

- Where op supports the following operators: =, !=, <, <=, >=, >
- and value to be quoted in single or double quotes when strings.


Example Query VMs name sample* and return name and vendor

```
GET /api/vms?expand=resources&attributes=name,vendor&filter"name='sample%'"
```

**Comment by abellotti** [comment]
Note, this is not on upstream yet.

**Comment by mfalesni** [comment]
@abellotti When I run this

https://machine/api/vms?expand=resources&attributes=name,vendor&filter=%22name=%27test%27%22

on 5.3.3.1, I get:

```{"error":{"kind":"internal_server_error","message":"private method `select' called for \"\\\"name='test'\\\"\":String","klass":"NoMethodError"}}```

**Comment by abellotti** [comment]
Odd, just tried on latest 5.3.z, without any issue. I see different characters surrounding the filter in the GET details.

Try using the api cli front-end and see if that helps.

```
api get vms --expand=resources --attributes=name,vendor --filter="name='test'"
```

api being a link to the cfme/lib/cfme_client/bin/rest_api.rb script.

you can also specify api --verbose get ... to see the details.

**Comment by mfalesni** [comment]
Thanks for pointing me out on the rest client. I found out that the `filter` is actually `filter[]`. Now it works when I pass it that way.

*P.S. I think I will have a python client for CFME to publish then, when it is finished :)*

**Comment by abellotti** [comment]
Ahh yes, forgot about the [], filter is a multi-param specification, I'll update the above write up. 
Thank you for trying it out.

**Comment by mfeifer** [comment]
@abellotti is this already done?

**Comment by abellotti** [comment]
blast from the past :) yep, it's in the docs for sure https://www.manageiq.org/docs/reference/latest/api/overview/filtering

Thanks @mfeifer for the winter cleaning.
