### ISSUE TITLE
[VOTE] Disable Naming/VariableNumber Cop

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/guides#497]
https://docs.rubocop.org/rubocop/1.19/cops_naming.html#namingvariablenumber

This cop is annoying particularly in specs.  What do you think about disabling entirely?  I'm not sure what we really gain by keeping it except that it's noise.

Example PR that shows the bot complaining about it: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/374, where it's complaining about these symbols: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/374/files#diff-d54a15a03812a47a8fca6738fa419467a30720611dd2f8bf976d99a120f8876eR35-R44

:+1: Disable completely
:-1: Keep as is
😕 Disable but only parts of it (such as only for symbols or only for method names)

**Comment by kbrock** [comment]
I recently changed a spec to get rid of numbers: `name_1`
Yes, it was annoying

**Comment by Fryguy** [comment]
Released in manageiq-style 1.3.2
